/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DatePanel.java
 *
 * Created on Mar 8, 2012, 9:38:08 PM
 */
package fp.views;

import javax.swing.ImageIcon;

import fp.models.DatePanelController;

/**
 *
 * @author Bart
 */
public class DatePanel extends javax.swing.JPanel {

    public final DatePanelController controller;
	/** Creates new form DatePanel */
    public DatePanel() {
        initComponents();
        this.controller = new DatePanelController(this);
    }
    
    public void validate() {
    	this.controller.redraw();
    	super.validate();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        meetingViewLayeredPane = new javax.swing.JLayeredPane();
        headerPanel = new javax.swing.JPanel();
        dateDayLabel = new javax.swing.JLabel();
        dayNameLabel = new javax.swing.JLabel();
        addNewMeetingButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panelBorder = new javax.swing.JSeparator();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fp.views.CalendarApp.class).getContext().getResourceMap(DatePanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setEnabled(false);
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        meetingViewLayeredPane.setName("meetingViewLayeredPane"); // NOI18N
        meetingViewLayeredPane.setOpaque(true);
        add(meetingViewLayeredPane, java.awt.BorderLayout.CENTER);

        headerPanel.setBackground(resourceMap.getColor("headerPanel.background")); // NOI18N
        headerPanel.setName("headerPanel"); // NOI18N
        headerPanel.setPreferredSize(new java.awt.Dimension(120, 40));

        dateDayLabel.setFont(resourceMap.getFont("dateDayLabel.font")); // NOI18N
        dateDayLabel.setText(resourceMap.getString("dateDayLabel.text")); // NOI18N
        dateDayLabel.setName("dateDayLabel"); // NOI18N

        dayNameLabel.setFont(resourceMap.getFont("dayNameLabel.font")); // NOI18N
        dayNameLabel.setText(resourceMap.getString("dayNameLabel.text")); // NOI18N
        dayNameLabel.setName("dayNameLabel"); // NOI18N

        addNewMeetingButton.setIcon(new ImageIcon("res/plus_small.png")); // NOI18N
        addNewMeetingButton.setText(resourceMap.getString("addNewMeetingButton.text")); // NOI18N
        addNewMeetingButton.setContentAreaFilled(false);
        addNewMeetingButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addNewMeetingButton.setName("addNewMeetingButton"); // NOI18N
        addNewMeetingButton.setRolloverIcon(new ImageIcon("res/plus_small2.png")); // NOI18N

        jSeparator2.setBackground(resourceMap.getColor("jSeparator2.background")); // NOI18N
        jSeparator2.setForeground(resourceMap.getColor("jSeparator2.foreground")); // NOI18N
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setName("jSeparator2"); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayNameLabel)
                    .addComponent(dateDayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(addNewMeetingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(dayNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDayLabel))
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(addNewMeetingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        panelBorder.setBackground(resourceMap.getColor("panelBorder.background")); // NOI18N
        panelBorder.setForeground(resourceMap.getColor("panelBorder.foreground")); // NOI18N
        panelBorder.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelBorder.setMinimumSize(new java.awt.Dimension(1, 10));
        panelBorder.setName("panelBorder"); // NOI18N
        panelBorder.setPreferredSize(new java.awt.Dimension(2, 10));
        add(panelBorder, java.awt.BorderLayout.EAST);
    }// </editor-fold>
    // Variables declaration - do not modify
    public javax.swing.JButton addNewMeetingButton;
    public javax.swing.JLabel dateDayLabel;
    public javax.swing.JLabel dayNameLabel;
    public javax.swing.JPanel headerPanel;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JLayeredPane meetingViewLayeredPane;
    public javax.swing.JSeparator panelBorder;
    // End of variables declaration
}

