/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewMeetingWindow.java
 *
 * Created on 09.mar.2012, 11:36:03
 */
package fp.views;

import javax.swing.ButtonGroup;
import javax.swing.JFrame;

import fp.components.InteractiveList;

/**
 *
 * @author Bart
 */
public class NewMeetingWindow extends javax.swing.JFrame {

	private static JFrame frame;
	/** Creates new form NewMeetingWindow */

	public NewMeetingWindow() {
		initComponents();
		frame = this;
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.setTitle("Add new meeting");
		ButtonGroup buttonGroup = new ButtonGroup();
		buttonGroup.add(NewMeetingWindow.newMeetingButton);
		buttonGroup.add(NewMeetingWindow.newAppointmentButton);
		this.participantsSearchInteractiveList = new InteractiveList<ParticipantSearchResultPanel>();
		this.participantSearchResultScrollPane.setViewportView(this.participantsSearchInteractiveList);
		this.invitedParticipantsInteractiveList = new InteractiveList<ParticipantListItemPanel>();
		this.invitedParticipantsScrollPane.setViewportView(this.invitedParticipantsInteractiveList);
	}

	public static void setFrameVisible(boolean enabled) {
		frame.setVisible(enabled);
		frame.setLocation(100, 100);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		createButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		appointmentTypeSectionPanel = new javax.swing.JPanel();
		appointmentTypeLabel = new javax.swing.JLabel();
		newMeetingButton = new javax.swing.JToggleButton();
		newAppointmentButton = new javax.swing.JToggleButton();
		appointmentTypeSeparator = new javax.swing.JSeparator();
		appointmentDetailsSectionPanel = new javax.swing.JPanel();
		appointmentDetailsSectionLabel = new javax.swing.JLabel();
		appointmentDetailsTitleLabel = new javax.swing.JLabel();
		appointmentTitleTextPane = new javax.swing.JTextPane();
		appointmentDetailsSeparator = new javax.swing.JSeparator();
		appointmentTimeSectionPanel = new javax.swing.JPanel();
		selectDateTimeSectionLabel = new javax.swing.JLabel();
		startTimeLabel = new javax.swing.JLabel();
		startDateTextPane = new javax.swing.JTextPane();
		endDateTextPane = new javax.swing.JTextPane();
		endDateLabel = new javax.swing.JLabel();
		startDateCalendarIcon = new javax.swing.JLabel();
		endDateCalendarIcon = new javax.swing.JLabel();
		startTimeTextPane = new javax.swing.JTextPane();
		endTimeTextPane = new javax.swing.JTextPane();
		selectDateTimeSeparator = new javax.swing.JSeparator();
		appointmentLocationSectionPanel = new javax.swing.JPanel();
		meetingLocationLabel = new javax.swing.JLabel();
		selectAvailableRoomLabel = new javax.swing.JLabel();
		meetingLocationDivisionOrLabel = new javax.swing.JLabel();
		locationSearchPanel = new javax.swing.JPanel();
		locationSearchMagnifyingGlassIcon = new javax.swing.JLabel();
		locationSearchTextPane = new javax.swing.JTextPane();
		meetingLocationVerticalDivider = new javax.swing.JSeparator();
		enterManualLocationLabel = new javax.swing.JLabel();
		manualLocationScrollPane = new javax.swing.JScrollPane();
		manualLocationTextPane = new javax.swing.JTextPane();
		meetingRoomSearchResultScrollPane = new javax.swing.JScrollPane();
		meetingRoomSearchResultList = new javax.swing.JList();
		selectedLocationDescriptionLabel = new javax.swing.JLabel();
		selectedLocationLabel = new javax.swing.JLabel();
		inviteParticipantsSectionSeparator = new javax.swing.JSeparator();
		appoiontmentParticipantsSectionPanel = new javax.swing.JPanel();
		inviteParticipantsSectionLabel = new javax.swing.JLabel();
		participantsSearchPanel = new javax.swing.JPanel();
		participantsSearchMagnifyingGlassIcon = new javax.swing.JLabel();
		participantSearchTextPane = new javax.swing.JTextPane();
		participantSearchResultScrollPane = new javax.swing.JScrollPane();
		participantSearchResultList = new javax.swing.JList();
		invitedParticipantsLabel = new javax.swing.JLabel();
		invitedParticipantsScrollPane = new javax.swing.JScrollPane();
		invitedParticipantsList = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setName("Form"); // NOI18N

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fp.views.CalendarApp.class).getContext().getResourceMap(NewMeetingWindow.class);
		createButton.setText(resourceMap.getString("createButton.text")); // NOI18N
		createButton.setName("createButton"); // NOI18N

		cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
		cancelButton.setName("cancelButton"); // NOI18N

		appointmentTypeSectionPanel.setName("appointmentTypeSectionPanel"); // NOI18N

		appointmentTypeLabel.setFont(resourceMap.getFont("appointmentTypeLabel.font")); // NOI18N
		appointmentTypeLabel.setText(resourceMap.getString("appointmentTypeLabel.text")); // NOI18N
		appointmentTypeLabel.setName("appointmentTypeLabel"); // NOI18N

		newMeetingButton.setText(resourceMap.getString("newMeetingButton.text")); // NOI18N
		newMeetingButton.setName("newMeetingButton"); // NOI18N

		newAppointmentButton.setText(resourceMap.getString("newAppointmentButton.text")); // NOI18N
		newAppointmentButton.setName("newAppointmentButton"); // NOI18N

		appointmentTypeSeparator.setName("appointmentTypeSeparator"); // NOI18N

		javax.swing.GroupLayout appointmentTypeSectionPanelLayout = new javax.swing.GroupLayout(appointmentTypeSectionPanel);
		appointmentTypeSectionPanel.setLayout(appointmentTypeSectionPanelLayout);
		appointmentTypeSectionPanelLayout.setHorizontalGroup(
				appointmentTypeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appointmentTypeSectionPanelLayout.createSequentialGroup()
						.addGroup(appointmentTypeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(appointmentTypeSectionPanelLayout.createSequentialGroup()
										.addContainerGap()
										.addComponent(appointmentTypeLabel))
										.addGroup(appointmentTypeSectionPanelLayout.createSequentialGroup()
												.addGap(61, 61, 61)
												.addComponent(newMeetingButton)
												.addGap(36, 36, 36)
												.addComponent(newAppointmentButton))
												.addGroup(appointmentTypeSectionPanelLayout.createSequentialGroup()
														.addContainerGap()
														.addComponent(appointmentTypeSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)))
														.addContainerGap())
		);
		appointmentTypeSectionPanelLayout.setVerticalGroup(
				appointmentTypeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appointmentTypeSectionPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(appointmentTypeLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(appointmentTypeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(newMeetingButton)
								.addComponent(newAppointmentButton))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
								.addComponent(appointmentTypeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		);

		appointmentDetailsSectionPanel.setName("appointmentDetailsSectionPanel"); // NOI18N

		appointmentDetailsSectionLabel.setFont(resourceMap.getFont("appointmentDetailsSectionLabel.font")); // NOI18N
		appointmentDetailsSectionLabel.setText(resourceMap.getString("appointmentDetailsSectionLabel.text")); // NOI18N
		appointmentDetailsSectionLabel.setName("appointmentDetailsSectionLabel"); // NOI18N

		appointmentDetailsTitleLabel.setText(resourceMap.getString("appointmentDetailsTitleLabel.text")); // NOI18N
		appointmentDetailsTitleLabel.setName("appointmentDetailsTitleLabel"); // NOI18N

		appointmentTitleTextPane.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("appointmentTitleTextPane.border.lineColor"))); // NOI18N
		appointmentTitleTextPane.setName("appointmentTitleTextPane"); // NOI18N
		appointmentTitleTextPane.setPreferredSize(new java.awt.Dimension(2, 20));

		appointmentDetailsSeparator.setName("appointmentDetailsSeparator"); // NOI18N

		javax.swing.GroupLayout appointmentDetailsSectionPanelLayout = new javax.swing.GroupLayout(appointmentDetailsSectionPanel);
		appointmentDetailsSectionPanel.setLayout(appointmentDetailsSectionPanelLayout);
		appointmentDetailsSectionPanelLayout.setHorizontalGroup(
				appointmentDetailsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appointmentDetailsSectionPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(appointmentDetailsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(appointmentDetailsSectionPanelLayout.createSequentialGroup()
										.addGap(10, 10, 10)
										.addComponent(appointmentDetailsTitleLabel)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(appointmentTitleTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(appointmentDetailsSectionLabel)
										.addComponent(appointmentDetailsSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
										.addContainerGap())
		);
		appointmentDetailsSectionPanelLayout.setVerticalGroup(
				appointmentDetailsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appointmentDetailsSectionPanelLayout.createSequentialGroup()
						.addComponent(appointmentDetailsSectionLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(appointmentDetailsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(appointmentDetailsTitleLabel)
								.addComponent(appointmentTitleTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(appointmentDetailsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		);

		appointmentTimeSectionPanel.setName("appointmentTimeSectionPanel"); // NOI18N

		selectDateTimeSectionLabel.setFont(resourceMap.getFont("selectDateTimeSectionLabel.font")); // NOI18N
		selectDateTimeSectionLabel.setText(resourceMap.getString("selectDateTimeSectionLabel.text")); // NOI18N
		selectDateTimeSectionLabel.setName("selectDateTimeSectionLabel"); // NOI18N

		startTimeLabel.setText(resourceMap.getString("startTimeLabel.text")); // NOI18N
		startTimeLabel.setName("startTimeLabel"); // NOI18N

		startDateTextPane.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("startDateTextPane.border.lineColor"))); // NOI18N
		startDateTextPane.setText(resourceMap.getString("startDateTextPane.text")); // NOI18N
		startDateTextPane.setName("startDateTextPane"); // NOI18N

		endDateTextPane.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("endDateTextPane.border.lineColor"))); // NOI18N
		endDateTextPane.setText(resourceMap.getString("endDateTextPane.text")); // NOI18N
		endDateTextPane.setName("endDateTextPane"); // NOI18N

		endDateLabel.setText(resourceMap.getString("endDateLabel.text")); // NOI18N
		endDateLabel.setName("endDateLabel"); // NOI18N

		startDateCalendarIcon.setIcon(resourceMap.getIcon("startDateCalendarIcon.icon")); // NOI18N
		startDateCalendarIcon.setText(resourceMap.getString("startDateCalendarIcon.text")); // NOI18N
		startDateCalendarIcon.setName("startDateCalendarIcon"); // NOI18N

		endDateCalendarIcon.setIcon(resourceMap.getIcon("endDateCalendarIcon.icon")); // NOI18N
		endDateCalendarIcon.setName("endDateCalendarIcon"); // NOI18N

		startTimeTextPane.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("startTimeTextPane.border.lineColor"))); // NOI18N
		startTimeTextPane.setText(resourceMap.getString("startTimeTextPane.text")); // NOI18N
		startTimeTextPane.setName("startTimeTextPane"); // NOI18N

		endTimeTextPane.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("endTimeTextPane.border.lineColor"))); // NOI18N
		endTimeTextPane.setText(resourceMap.getString("endTimeTextPane.text")); // NOI18N
		endTimeTextPane.setName("endTimeTextPane"); // NOI18N

		selectDateTimeSeparator.setName("selectDateTimeSeparator"); // NOI18N

		javax.swing.GroupLayout appointmentTimeSectionPanelLayout = new javax.swing.GroupLayout(appointmentTimeSectionPanel);
		appointmentTimeSectionPanel.setLayout(appointmentTimeSectionPanelLayout);
		appointmentTimeSectionPanelLayout.setHorizontalGroup(
				appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appointmentTimeSectionPanelLayout.createSequentialGroup()
						.addGroup(appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(appointmentTimeSectionPanelLayout.createSequentialGroup()
										.addContainerGap()
										.addComponent(selectDateTimeSectionLabel))
										.addGroup(appointmentTimeSectionPanelLayout.createSequentialGroup()
												.addGap(20, 20, 20)
												.addGroup(appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(endDateLabel)
														.addComponent(startTimeLabel))
														.addGap(18, 18, 18)
														.addGroup(appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addGroup(appointmentTimeSectionPanelLayout.createSequentialGroup()
																		.addComponent(startDateTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(startDateCalendarIcon)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(startTimeTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(appointmentTimeSectionPanelLayout.createSequentialGroup()
																				.addComponent(endDateTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(endDateCalendarIcon)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(endTimeTextPane))))
																				.addGroup(appointmentTimeSectionPanelLayout.createSequentialGroup()
																						.addContainerGap()
																						.addComponent(selectDateTimeSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)))
																						.addContainerGap())
		);
		appointmentTimeSectionPanelLayout.setVerticalGroup(
				appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appointmentTimeSectionPanelLayout.createSequentialGroup()
						.addComponent(selectDateTimeSectionLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(startTimeTextPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(startDateCalendarIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(startDateTextPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
										.addComponent(startTimeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(appointmentTimeSectionPanelLayout.createSequentialGroup()
														.addGroup(appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(endTimeTextPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
																.addGroup(appointmentTimeSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																		.addComponent(endDateCalendarIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(endDateTextPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
																		.addGap(4, 4, 4))
																		.addGroup(javax.swing.GroupLayout.Alignment.LEADING, appointmentTimeSectionPanelLayout.createSequentialGroup()
																				.addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																				.addComponent(selectDateTimeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		);

		appointmentLocationSectionPanel.setName("appointmentLocationSectionPanel"); // NOI18N

		meetingLocationLabel.setFont(resourceMap.getFont("meetingLocationLabel.font")); // NOI18N
		meetingLocationLabel.setText(resourceMap.getString("meetingLocationLabel.text")); // NOI18N
		meetingLocationLabel.setName("meetingLocationLabel"); // NOI18N

		selectAvailableRoomLabel.setText(resourceMap.getString("selectAvailableRoomLabel.text")); // NOI18N
		selectAvailableRoomLabel.setName("selectAvailableRoomLabel"); // NOI18N

		meetingLocationDivisionOrLabel.setFont(resourceMap.getFont("meetingLocationDivisionOrLabel.font")); // NOI18N
		meetingLocationDivisionOrLabel.setText(resourceMap.getString("meetingLocationDivisionOrLabel.text")); // NOI18N
		meetingLocationDivisionOrLabel.setName("meetingLocationDivisionOrLabel"); // NOI18N

		locationSearchPanel.setBackground(resourceMap.getColor("locationSearchPanel.background")); // NOI18N
		locationSearchPanel.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("locationSearchPanel.border.lineColor"))); // NOI18N
		locationSearchPanel.setName("locationSearchPanel"); // NOI18N
		locationSearchPanel.setPreferredSize(new java.awt.Dimension(136, 24));

		locationSearchMagnifyingGlassIcon.setBackground(resourceMap.getColor("locationSearchMagnifyingGlassIcon.background")); // NOI18N
		locationSearchMagnifyingGlassIcon.setIcon(resourceMap.getIcon("locationSearchMagnifyingGlassIcon.icon")); // NOI18N
		locationSearchMagnifyingGlassIcon.setText(resourceMap.getString("locationSearchMagnifyingGlassIcon.text")); // NOI18N
		locationSearchMagnifyingGlassIcon.setIconTextGap(0);
		locationSearchMagnifyingGlassIcon.setName("locationSearchMagnifyingGlassIcon"); // NOI18N

		locationSearchTextPane.setBorder(null);
		locationSearchTextPane.setName("locationSearchTextPane"); // NOI18N
		locationSearchTextPane.setPreferredSize(new java.awt.Dimension(6, 18));

		javax.swing.GroupLayout locationSearchPanelLayout = new javax.swing.GroupLayout(locationSearchPanel);
		locationSearchPanel.setLayout(locationSearchPanelLayout);
		locationSearchPanelLayout.setHorizontalGroup(
				locationSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, locationSearchPanelLayout.createSequentialGroup()
						.addComponent(locationSearchTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(locationSearchMagnifyingGlassIcon))
		);
		locationSearchPanelLayout.setVerticalGroup(
				locationSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(locationSearchMagnifyingGlassIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
				.addGroup(locationSearchPanelLayout.createSequentialGroup()
						.addComponent(locationSearchTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
						.addGap(2, 2, 2))
		);

		meetingLocationVerticalDivider.setOrientation(javax.swing.SwingConstants.VERTICAL);
		meetingLocationVerticalDivider.setName("meetingLocationVerticalDivider"); // NOI18N

		enterManualLocationLabel.setText(resourceMap.getString("enterManualLocationLabel.text")); // NOI18N
		enterManualLocationLabel.setName("enterManualLocationLabel"); // NOI18N

		manualLocationScrollPane.setName("manualLocationScrollPane"); // NOI18N

		manualLocationTextPane.setName("manualLocationTextPane"); // NOI18N
		manualLocationScrollPane.setViewportView(manualLocationTextPane);

		meetingRoomSearchResultScrollPane.setName("meetingRoomSearchResultScrollPane"); // NOI18N

		meetingRoomSearchResultList.setName("meetingRoomSearchResultList"); // NOI18N
		meetingRoomSearchResultScrollPane.setViewportView(meetingRoomSearchResultList);

		selectedLocationDescriptionLabel.setText(resourceMap.getString("selectedLocationDescriptionLabel.text")); // NOI18N
		selectedLocationDescriptionLabel.setName("selectedLocationDescriptionLabel"); // NOI18N

		selectedLocationLabel.setText(resourceMap.getString("selectedLocationLabel.text")); // NOI18N
		selectedLocationLabel.setName("selectedLocationLabel"); // NOI18N

		inviteParticipantsSectionSeparator.setName("inviteParticipantsSectionSeparator"); // NOI18N

		javax.swing.GroupLayout appointmentLocationSectionPanelLayout = new javax.swing.GroupLayout(appointmentLocationSectionPanel);
		appointmentLocationSectionPanel.setLayout(appointmentLocationSectionPanelLayout);
		appointmentLocationSectionPanelLayout.setHorizontalGroup(
				appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appointmentLocationSectionPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(inviteParticipantsSectionSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
								.addGroup(appointmentLocationSectionPanelLayout.createSequentialGroup()
										.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(meetingLocationLabel)
												.addGroup(appointmentLocationSectionPanelLayout.createSequentialGroup()
														.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(selectAvailableRoomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
																.addComponent(locationSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
																.addComponent(meetingRoomSearchResultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(appointmentLocationSectionPanelLayout.createSequentialGroup()
																				.addGap(2, 2, 2)
																				.addComponent(meetingLocationVerticalDivider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(manualLocationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(enterManualLocationLabel)))
																						.addComponent(meetingLocationDivisionOrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGroup(appointmentLocationSectionPanelLayout.createSequentialGroup()
																								.addComponent(selectedLocationDescriptionLabel)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(selectedLocationLabel)))
																								.addContainerGap())))
		);
		appointmentLocationSectionPanelLayout.setVerticalGroup(
				appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appointmentLocationSectionPanelLayout.createSequentialGroup()
						.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(appointmentLocationSectionPanelLayout.createSequentialGroup()
										.addGap(20, 20, 20)
										.addComponent(meetingLocationDivisionOrLabel))
										.addComponent(meetingLocationLabel))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(appointmentLocationSectionPanelLayout.createSequentialGroup()
														.addComponent(enterManualLocationLabel)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(manualLocationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																.addComponent(meetingLocationVerticalDivider, javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(javax.swing.GroupLayout.Alignment.LEADING, appointmentLocationSectionPanelLayout.createSequentialGroup()
																		.addComponent(selectAvailableRoomLabel)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(locationSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(meetingRoomSearchResultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(appointmentLocationSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(selectedLocationDescriptionLabel)
																				.addComponent(selectedLocationLabel))
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																				.addComponent(inviteParticipantsSectionSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(10, 10, 10))
		);

		appoiontmentParticipantsSectionPanel.setName("appoiontmentParticipantsSectionPanel"); // NOI18N

		inviteParticipantsSectionLabel.setFont(resourceMap.getFont("inviteParticipantsSectionLabel.font")); // NOI18N
		inviteParticipantsSectionLabel.setText(resourceMap.getString("inviteParticipantsSectionLabel.text")); // NOI18N
		inviteParticipantsSectionLabel.setName("inviteParticipantsSectionLabel"); // NOI18N

		participantsSearchPanel.setBackground(resourceMap.getColor("participantsSearchPanel.background")); // NOI18N
		participantsSearchPanel.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("participantsSearchPanel.border.lineColor"))); // NOI18N
		participantsSearchPanel.setName("participantsSearchPanel"); // NOI18N
		participantsSearchPanel.setPreferredSize(new java.awt.Dimension(136, 24));

		participantsSearchMagnifyingGlassIcon.setBackground(resourceMap.getColor("participantsSearchMagnifyingGlassIcon.background")); // NOI18N
		participantsSearchMagnifyingGlassIcon.setIcon(resourceMap.getIcon("participantsSearchMagnifyingGlassIcon.icon")); // NOI18N
		participantsSearchMagnifyingGlassIcon.setText(resourceMap.getString("participantsSearchMagnifyingGlassIcon.text")); // NOI18N
		participantsSearchMagnifyingGlassIcon.setIconTextGap(0);
		participantsSearchMagnifyingGlassIcon.setName("participantsSearchMagnifyingGlassIcon"); // NOI18N

		participantSearchTextPane.setBorder(null);
		participantSearchTextPane.setName("participantSearchTextPane"); // NOI18N
		participantSearchTextPane.setPreferredSize(new java.awt.Dimension(6, 18));

		javax.swing.GroupLayout participantsSearchPanelLayout = new javax.swing.GroupLayout(participantsSearchPanel);
		participantsSearchPanel.setLayout(participantsSearchPanelLayout);
		participantsSearchPanelLayout.setHorizontalGroup(
				participantsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, participantsSearchPanelLayout.createSequentialGroup()
						.addComponent(participantSearchTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(participantsSearchMagnifyingGlassIcon))
		);
		participantsSearchPanelLayout.setVerticalGroup(
				participantsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(participantsSearchMagnifyingGlassIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
				.addComponent(participantSearchTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
		);

		participantSearchResultScrollPane.setName("participantSearchResultScrollPane"); // NOI18N

		participantSearchResultList.setName("participantSearchResultList"); // NOI18N
		participantSearchResultScrollPane.setViewportView(participantSearchResultList);

		invitedParticipantsLabel.setText(resourceMap.getString("invitedParticipantsLabel.text")); // NOI18N
		invitedParticipantsLabel.setName("invitedParticipantsLabel"); // NOI18N

		invitedParticipantsScrollPane.setName("invitedParticipantsScrollPane"); // NOI18N

		invitedParticipantsList.setName("invitedParticipantsList"); // NOI18N
		invitedParticipantsScrollPane.setViewportView(invitedParticipantsList);

		javax.swing.GroupLayout appoiontmentParticipantsSectionPanelLayout = new javax.swing.GroupLayout(appoiontmentParticipantsSectionPanel);
		appoiontmentParticipantsSectionPanel.setLayout(appoiontmentParticipantsSectionPanelLayout);
		appoiontmentParticipantsSectionPanelLayout.setHorizontalGroup(
				appoiontmentParticipantsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appoiontmentParticipantsSectionPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(appoiontmentParticipantsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(participantSearchResultScrollPane, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
								.addComponent(inviteParticipantsSectionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(participantsSearchPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(appoiontmentParticipantsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(invitedParticipantsLabel)
										.addComponent(invitedParticipantsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap())
		);
		appoiontmentParticipantsSectionPanelLayout.setVerticalGroup(
				appoiontmentParticipantsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(appoiontmentParticipantsSectionPanelLayout.createSequentialGroup()
						.addComponent(inviteParticipantsSectionLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(appoiontmentParticipantsSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(appoiontmentParticipantsSectionPanelLayout.createSequentialGroup()
										.addComponent(invitedParticipantsLabel)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(invitedParticipantsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(appoiontmentParticipantsSectionPanelLayout.createSequentialGroup()
												.addComponent(participantsSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(participantSearchResultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(appointmentTimeSectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(appointmentDetailsSectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(appointmentTypeSectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
						.addComponent(appointmentLocationSectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(20, Short.MAX_VALUE))
						.addComponent(appoiontmentParticipantsSectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap(225, Short.MAX_VALUE)
								.addComponent(cancelButton)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(createButton)
								.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(appointmentTypeSectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(appointmentDetailsSectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(appointmentTimeSectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(appointmentLocationSectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(appoiontmentParticipantsSectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(createButton)
								.addComponent(cancelButton))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public static javax.swing.JLabel appointmentDetailsSectionLabel;
	public static javax.swing.JPanel appointmentDetailsSectionPanel;
	public static javax.swing.JSeparator appointmentDetailsSeparator;
	public static javax.swing.JLabel appointmentDetailsTitleLabel;
	public static javax.swing.JPanel appointmentLocationSectionPanel;
	public static javax.swing.JPanel appointmentTimeSectionPanel;
	public static javax.swing.JTextPane appointmentTitleTextPane;
	public static javax.swing.JLabel appointmentTypeLabel;
	public static javax.swing.JPanel appointmentTypeSectionPanel;
	public static javax.swing.JSeparator appointmentTypeSeparator;
	public static javax.swing.JPanel appoiontmentParticipantsSectionPanel;
	public static javax.swing.JButton cancelButton;
	public static javax.swing.JButton createButton;
	public static javax.swing.JLabel endDateCalendarIcon;
	public static javax.swing.JLabel endDateLabel;
	public static javax.swing.JTextPane endDateTextPane;
	public static javax.swing.JTextPane endTimeTextPane;
	public static javax.swing.JLabel enterManualLocationLabel;
	public static javax.swing.JLabel inviteParticipantsSectionLabel;
	public static javax.swing.JSeparator inviteParticipantsSectionSeparator;
	public static javax.swing.JLabel invitedParticipantsLabel;
	private static javax.swing.JList invitedParticipantsList;
	public static javax.swing.JScrollPane invitedParticipantsScrollPane;
	public static javax.swing.JLabel locationSearchMagnifyingGlassIcon;
	public static javax.swing.JPanel locationSearchPanel;
	public static javax.swing.JTextPane locationSearchTextPane;
	public static javax.swing.JScrollPane manualLocationScrollPane;
	public static javax.swing.JTextPane manualLocationTextPane;
	public static javax.swing.JLabel meetingLocationDivisionOrLabel;
	public static javax.swing.JLabel meetingLocationLabel;
	public static javax.swing.JSeparator meetingLocationVerticalDivider;
	public static javax.swing.JList meetingRoomSearchResultList;
	public static javax.swing.JScrollPane meetingRoomSearchResultScrollPane;
	public static javax.swing.JToggleButton newAppointmentButton;
	public static javax.swing.JToggleButton newMeetingButton;
	private static javax.swing.JList participantSearchResultList;
	public static javax.swing.JScrollPane participantSearchResultScrollPane;
	public static javax.swing.JTextPane participantSearchTextPane;
	public static javax.swing.JLabel participantsSearchMagnifyingGlassIcon;
	public static javax.swing.JPanel participantsSearchPanel;
	public static javax.swing.JLabel selectAvailableRoomLabel;
	public static javax.swing.JLabel selectDateTimeSectionLabel;
	public static javax.swing.JSeparator selectDateTimeSeparator;
	public static javax.swing.JLabel selectedLocationDescriptionLabel;
	public static javax.swing.JLabel selectedLocationLabel;
	public static javax.swing.JLabel startDateCalendarIcon;
	public static javax.swing.JTextPane startDateTextPane;
	public static javax.swing.JLabel startTimeLabel;
	public static javax.swing.JTextPane startTimeTextPane;
	// End of variables declaration//GEN-END:variables

	public static InteractiveList<ParticipantSearchResultPanel> participantsSearchInteractiveList;
	public static InteractiveList<ParticipantListItemPanel> invitedParticipantsInteractiveList;
}
