/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SmallCalendar.java
 *
 * Created on Mar 11, 2012, 11:34:37 AM
 */
package fp.views;

import java.awt.Color;

import javax.swing.ListSelectionModel;

import fp.components.smallCalendar.SmallCalendarTableTableCellRenderer;

/**
 *
 * @author Bart
 */
public class SmallCalendarPanel extends javax.swing.JPanel {

	/** Creates new form SmallCalendar */
	public SmallCalendarPanel() {
		initComponents();
		SmallCalendarPanel.calendarTable.getColumnModel().setColumnMargin(0);
		SmallCalendarPanel.calendarTable.getTableHeader().setEnabled(false);
		SmallCalendarPanel.calendarTable.setDefaultRenderer(Object.class, new SmallCalendarTableTableCellRenderer());
		SmallCalendarPanel.calendarTable.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		prevMonthButton = new javax.swing.JButton();
		nextMonthButton = new javax.swing.JButton();
		monthLabel = new javax.swing.JLabel();
		tableScrollPane = new javax.swing.JScrollPane();
		calendarTable = new javax.swing.JTable();

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fp.views.CalendarApp.class).getContext().getResourceMap(SmallCalendarPanel.class);
		setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("Form.border.lineColor"))); // NOI18N
		setName("Form"); // NOI18N

		prevMonthButton.setText(resourceMap.getString("prevMonthButton.text")); // NOI18N
		prevMonthButton.setMargin(new java.awt.Insets(1, 4, 1, 4));
		prevMonthButton.setName("prevMonthButton"); // NOI18N

		nextMonthButton.setText(resourceMap.getString("nextMonthButton.text")); // NOI18N
		nextMonthButton.setMargin(new java.awt.Insets(1, 4, 1, 4));
		nextMonthButton.setName("nextMonthButton"); // NOI18N

		monthLabel.setFont(resourceMap.getFont("monthLabel.font")); // NOI18N
		monthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		monthLabel.setText(resourceMap.getString("monthLabel.text")); // NOI18N
		monthLabel.setName("monthLabel"); // NOI18N

		tableScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		tableScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
		tableScrollPane.setName("tableScrollPane"); // NOI18N

		calendarTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
						{null, null, null, null, null, null, null},
						{null, null, null, null, null, null, null},
						{null, null, null, null, null, null, null},
						{null, null, null, null, null, null, null}
				},
				new String [] {
						"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"
				}
				) {
			boolean[] canEdit = new boolean [] {
					false, false, false, false, false, false, false
			};

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit [columnIndex];
			}
		});
		calendarTable.setName("calendarTable"); // NOI18N
		calendarTable.setShowHorizontalLines(false);
		calendarTable.setShowVerticalLines(false);
		calendarTable.getTableHeader().setResizingAllowed(false);
		calendarTable.getTableHeader().setReorderingAllowed(false);
		tableScrollPane.setViewportView(calendarTable);
		calendarTable.getColumnModel().getColumn(0).setResizable(false);
		calendarTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title0")); // NOI18N
		calendarTable.getColumnModel().getColumn(1).setResizable(false);
		calendarTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title1")); // NOI18N
		calendarTable.getColumnModel().getColumn(2).setResizable(false);
		calendarTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title2")); // NOI18N
		calendarTable.getColumnModel().getColumn(3).setResizable(false);
		calendarTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title3")); // NOI18N
		calendarTable.getColumnModel().getColumn(4).setResizable(false);
		calendarTable.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title4")); // NOI18N
		calendarTable.getColumnModel().getColumn(5).setResizable(false);
		calendarTable.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title5")); // NOI18N
		calendarTable.getColumnModel().getColumn(6).setResizable(false);
		calendarTable.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title6")); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
										.addComponent(prevMonthButton)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(monthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(nextMonthButton)))
										.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(prevMonthButton)
								.addComponent(monthLabel)
								.addComponent(nextMonthButton))
								.addContainerGap())
				);
	}// </editor-fold>
	// Variables declaration - do not modify
	public static javax.swing.JTable calendarTable;
	public static  javax.swing.JLabel monthLabel;
	public static  javax.swing.JButton nextMonthButton;
	public static  javax.swing.JButton prevMonthButton;
	public static  javax.swing.JScrollPane tableScrollPane;
	// End of variables declaration
}

