package fp.componentControllers;

public enum ComponentControllerType {
	CALENDAR_VIEW_SMALL_CALENDAR,
	CALENDAR_VIEW_FAVOURITES,
	CALENDAR_VIEW_SEARCH,
	CALENDAR_VIEW_NOTIFICATIONS,
	CALENDAR_VIEW_CALENDAR
}
