/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SmallCalendar.java
 *
 * Created on Mar 11, 2012, 11:34:37 AM
 */
package prototype.calendarApp.views;

/**
 *
 * @author Bart
 */
public class SmallCalendar extends javax.swing.JPanel {

    /** Creates new form SmallCalendar */
    public SmallCalendar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prevMonthButton = new javax.swing.JButton();
        calendarTable = new javax.swing.JTable();
        nextMonthButton = new javax.swing.JButton();
        monthLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(prototype.calendarApp.views.CalendarApp.class).getContext().getResourceMap(SmallCalendar.class);
        setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("Form.border.lineColor"))); // NOI18N
        setName("Form"); // NOI18N

        prevMonthButton.setText(resourceMap.getString("prevMonthButton.text")); // NOI18N
        prevMonthButton.setMargin(new java.awt.Insets(1, 4, 1, 4));
        prevMonthButton.setName("prevMonthButton"); // NOI18N

        calendarTable.setBackground(resourceMap.getColor("calendarTable.background")); // NOI18N
        calendarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"},
                {null, null, "", "", "", "1", "2"},
                {"3", "4", "5", "6", "7", "8", "9"},
                {"10", "11", "12", "13", "14", "15", "16"},
                {"17", "18", "19", "20", "21", "22", "23"},
                {"24", "25", "26", "27", "28", "29", "30"},
                {"31", null, null, null, null, null, null}
            },
            new String [] {
                "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calendarTable.setName("calendarTable"); // NOI18N
        calendarTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        calendarTable.setShowHorizontalLines(false);
        calendarTable.setShowVerticalLines(false);
        calendarTable.setTableHeader(null);

        nextMonthButton.setText(resourceMap.getString("nextMonthButton.text")); // NOI18N
        nextMonthButton.setMargin(new java.awt.Insets(1, 4, 1, 4));
        nextMonthButton.setName("nextMonthButton"); // NOI18N

        monthLabel.setFont(resourceMap.getFont("monthLabel.font")); // NOI18N
        monthLabel.setText(resourceMap.getString("monthLabel.text")); // NOI18N
        monthLabel.setName("monthLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calendarTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(monthLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(prevMonthButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(nextMonthButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(monthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarTable, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevMonthButton)
                    .addComponent(nextMonthButton))
                .addContainerGap())
        );

        calendarTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title0")); // NOI18N
        calendarTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title1")); // NOI18N
        calendarTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title2")); // NOI18N
        calendarTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title3")); // NOI18N
        calendarTable.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title4")); // NOI18N
        calendarTable.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title5")); // NOI18N
        calendarTable.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("calendarTable.columnModel.title6")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable calendarTable;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JButton nextMonthButton;
    private javax.swing.JButton prevMonthButton;
    // End of variables declaration//GEN-END:variables
}
