package fp.events;

public enum EventType {
	WINDOW_RESIZED, 
	SELECTED_WEEK_CHANGED, 
	SERVER_MEETING_REGISTERED, 
	NOTIFICATION_RECEIVED, 
	NO_NEW_NOTIFICATIONS, 
	SHOW_NEW_MEETING, 
	NOTIFICATIONS_UPDATE_REQUESTED,
	SEARCH_MEETINGROOM_RESULT
}
