package fp.componentHandlers;

public enum ComponentHandlerType {
	CALENDAR_VIEW_SMALL_CALENDAR,
	CALENDAR_VIEW_FAVOURITES,
	CALENDAR_VIEW_SEARCH,
	CALENDAR_VIEW_NOTIFICATIONS,
	CALENDAR_VIEW_CALENDAR,
	CALENDAR_VIEW_WINDOW_RESIZE
}
